name: ci

on:
  push:
    branches-ignore:
    - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch variable
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      
      - name: Extract revision variable
        run: echo "GIT_REVISION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR as ${{ github.actor }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Required to mount the Github Workspace to a volume 
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Build static content
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/wirenboard/website-base-image:initial
          options: -v ${{ github.workspace }}:/var/www -e ABC=123
          run: |
            cd /var/www
            pnpm install
            pnpm run build
            
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,arm64
          tags: |
            ghcr.io/wirenboard/website:${{ env.BRANCH }}-${{ env.GIT_REVISION }}
            ghcr.io/wirenboard/website:${{ env.BRANCH }}
